Repository TileDB-Inc/TileDB-Py, pull requests merged in 2018-07, with the labels that each got.

#48 Rework setup process to download/install TileDB if necessary.
  .gitignore
  .travis.yml
  MANIFEST.in
  README.rst
  requirements_dev.txt
  setup.py
  tiledb/__init__.py
Labels: build

#50 Documentation work and misc small fixes.
  .travis.yml
  README.rst
  doc/source/python-api.rst
  examples/quickstart_dense.py
  examples/quickstart_kv.py
  examples/quickstart_sparse.py
  tiledb/__init__.py
  tiledb/libtiledb.pyx
Labels: documentation

#51 README/doc tweaks and add license text to quickstarts.
  README.rst
  examples/quickstart_dense.py
  examples/quickstart_kv.py
  examples/quickstart_sparse.py
  tiledb/libtiledb.pyx
Labels: documentation

#52 Docs, installation and dependency fixes
  .travis.yml
  MANIFEST.in
  doc/source/conda-env.yml
  requirements.txt
  requirements_dev.txt
  setup.py
  tiledb/libtiledb.pyx
Labels: CI, build, documentation

#53 Two small quickstart fixes
  examples/quickstart_kv.py
  examples/quickstart_sparse.py
Labels: documentation

#59 Add several new examples, and two missing bindings (w/ tests).
  .travis.yml
  README.rst
  doc/source/python-api.rst
  examples/config.py
  examples/errors.py
  examples/fragments_consolidation.py
  examples/kv.py
  examples/libtiledb/.gitignore
  examples/libtiledb/tiledb_array_consolidate.py
  examples/libtiledb/tiledb_array_schema.py
  examples/libtiledb/tiledb_config.py
  examples/libtiledb/tiledb_dense_create.py
  examples/libtiledb/tiledb_dense_read.py
  examples/libtiledb/tiledb_dense_read_subarray.py
  examples/libtiledb/tiledb_dense_write.py
  examples/libtiledb/tiledb_dense_write_subarray.py
  examples/libtiledb/tiledb_error.py
  examples/libtiledb/tiledb_group_create.py
  examples/libtiledb/tiledb_kv.py
  examples/libtiledb/tiledb_object_ls_walk.py
  examples/libtiledb/tiledb_object_move.py
  examples/libtiledb/tiledb_object_remove.py
  examples/libtiledb/tiledb_object_type.py
  examples/libtiledb/tiledb_sparse_create.py
  examples/libtiledb/tiledb_sparse_read.py
  examples/libtiledb/tiledb_sparse_read_subarray.py
  examples/libtiledb/tiledb_sparse_write.py
  examples/libtiledb/tiledb_version.py
  examples/libtiledb/tiledb_vfs.py
  examples/libtiledb/tiledb_vfs_read.py
  examples/libtiledb/tiledb_vfs_write.py
  examples/multi_attribute.py
  examples/object.py
  examples/vfs.py
  tiledb/__init__.py
  tiledb/libtiledb.pxd
  tiledb/libtiledb.pyx
  tiledb/tests/test_libtiledb.py
Labels: API addition, CI, documentation

#61 Minor edits in examples
  examples/quickstart_dense.py
  examples/quickstart_kv.py
  examples/quickstart_sparse.py
  examples/writing_dense_multiple.py
  examples/writing_dense_padding.py
  examples/writing_sparse_multiple.py
Labels: examples

#63 Minor edits in examples and Attr() docstring
  examples/config.py
  tiledb/libtiledb.pyx
Labels: documentation, examples

#65 Sync sidebar; bump docs version num; small docstring fixes.
  doc/source/conf.py
  doc/source/gensidebar.py
  tiledb/libtiledb.pyx
Labels: documentation

#66 Fix example tutorial URLs
  examples/config.py
  examples/errors.py
  examples/fragments_consolidation.py
  examples/kv.py
  examples/multi_attribute.py
  examples/object.py
  examples/quickstart_dense.py
  examples/quickstart_kv.py
  examples/quickstart_sparse.py
  examples/reading_dense_layouts.py
  examples/reading_sparse_layouts.py
  examples/using_tiledb_stats.py
  examples/vfs.py
  examples/writing_dense_multiple.py
  examples/writing_dense_padding.py
  examples/writing_sparse_multiple.py
Labels: documentation
